### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by jw1123** [Yaafe/Yaafe#1]
Hi,

I try to run yaafe.py, but when I do so I get this error message:

` File "yaafe.py", line 32, in <module>
    import yaafelib as yaafe
  File "/Users/jw/yaafe/python_packages/yaafelib/__init__.py", line 36, in <module>
    from core import *
  File "/Users/jw/yaafe/python_packages/yaafelib/core.py", line 52, in <module>
    yaafecore.destroyFactory.restype = None
  File "/Users/jw/anaconda/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/Users/jw/anaconda/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x1003a3db0, destroyFactory): symbol not found`

Now in core.py I replaced line 29 `yaafecore = cdll.LoadLibrary(path/to/libyaafecore.so)` with `yaafecore = cdll.LoadLibrary(path/to/libyaafe-core.0.dylib)` because it asked me to do this first when I tried to run yaafe.py.

Can somebody help me to solve this problem?

**Comment by Crococode** [comment]
In the latest code libyaafe-python.so is linked at this point.
This can probably be closed.

**Comment by thomasfillon** [comment]
@jw1123 : I close this because it seems fixed now but don't hesitate to reopen it if you still have the same problem.
