### ISSUE TITLE
ERROR: dataflow must have exactly 1 root node

### ISSUE THREAD

**Issue by geniass** [Yaafe/Yaafe#10]
I have tried building Yaafe following the instructions on Sourceforge and Github, as well as with the install.sh script. I have installed: `sudo apt-get install cmake cmake-curses-gui libargtable2-0 libargtable2-dev libsndfile1 libsndfile1-dev libmpg123-0 libmpg123-dev libfftw3-3 libfftw3-dev liblapack-dev` so Yaafe compiles and installs fine. $YAAFEPATH is set to `/usr/lib/python2.7/dist-packages/yaafelib/yaafe_extensions`.

If I run yaafe, for example `yaafe "mfcc: MFCC blockSize=1024 stepSize=512" test.wav`, I keep getting `ERROR: dataflow must have exactly 1 root node`. This happens with any of the features. test.wav is just a sine wave I generated with Audacity, but I get the same error with any file including mp3's.

Are there any other logs I can post?

**Comment by geniass** [comment]
The problem was I left out the `-f` option by mistake. So it's user error, but there should be a more helpful error message.

**Comment by thomasfillon** [comment]
OK thank you for your feedback on this
