### ISSUE TITLE
Dockerfile?

### ISSUE THREAD

**Issue by hbredin** [Yaafe/Yaafe#14]
Since `yaafe` is not yet `pip`-installable, a sample `Dockerfile` based on `ubuntu` or `debian` would be great :-)

**Comment by thomasfillon** [comment]
Hi Hervé 
You're a mind reader ;) 

I'm also thinking of building a conda package.

**Comment by hbredin** [comment]
Here is a first draft.

```
FROM ubuntu:trusty
MAINTAINER Thomas Fillon <fillon@fillon.com>

RUN apt-get update
RUN apt-get install -y python-pip python-dev build-essential python-numpy
RUN apt-get install -y cmake cmake-curses-gui libargtable2-0 libargtable2-dev libsndfile1 libsndfile1-dev libmpg123-0 libmpg123-dev libfftw3-3 libfftw3-dev liblapack-dev libh\
df5-serial-dev wget

RUN wget https://github.com/Yaafe/Yaafe/archive/v0.65.1.tar.gz && \
    tar xzvf v0.65.1.tar.gz && \
    cd Yaafe-0.65.1 && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DCMAKE_INSTALL_PYTHON_PACKAGES=/usr/local/lib/python2.7/dist-packages \
          -DCMAKE_INSTALL_YAAFE_EXTENSIONS=/usr/local/lib/python2.7/dist-packages \
          -DWITH_FFTW3=ON \
          -DWITH_HDF5=ON \
          -DWITH_LAPACK=ON \
          -DWITH_MATLAB_MEX=OFF \
          -DWITH_MPG123=ON \
          -DWITH_SNDFILE=ON \
          .. && \
    make && \
    make install && \
    cd ../.. && \
    rm -rf Yaafe-0.65.1 v0.65.1.tar.gz

ENV LD_LIBRARY_PATH /usr/local/lib
ENV YAAFE_PATH /usr/local/lib/python2.7/dist-packages

CMD ["/usr/local/bin/yaafe", "--help"]
```

**Comment by thomasfillon** [comment]
> MAINTAINER Thomas Fillon <fillon@fillon.com>

Sadly I do not own that domain name ;)

**Comment by thomasfillon** [comment]
... almost there ... ;)

**Comment by thomasfillon** [comment]
Fix on the Dev branch for the 0.70 first release candidate.
See the Readme for more details.
@hbredin  does it seems OK to you (documentation and usage ) ?

**Comment by thomasfillon** [comment]
See also these 2 other Docker images including Yaafe:
- [yaafe-docker on GitHub](https://hub.docker.com/r/nicktgr15/yaafe-docker/) or [yaafe-docker on Docker Hub](https://github.com/nicktgr15/yaafe-docker) by @nicktgr15 
- [pyannote-docker on Github](https://github.com/pyannote/pyannote-docker) or [pyannote/base-audiovisual on Docker Hub](https://hub.docker.com/r/pyannote/base-audiovisual/) by @hbredin

**Comment by hbredin** [comment]
LGTM :-)

**Comment by thomasfillon** [comment]
Great thank you !
