### ISSUE TITLE
Segmentation fault with a certain file when re-sampling  

### ISSUE THREAD

**Issue by PGryllos** [Yaafe/Yaafe#15]
I am trying to apply MFFC to a dataset with the following plan 

    def extractFeatures(audiofile):
        fp = FeaturePlan(sample_rate=44100, resample=True)
        fp.addFeature('mfcc: MFCC blockSize=512 stepSize=256')
        df = fp.getDataFlow()
        engine = Engine()
        engine.load(df)
        afp = AudioFileProcessor()
        afp.processFile(engine,audiofile)
        features = engine.readAllOutputs()
        return features

and I get a segmentation fault.

But only when I set the sample rate to 44100 I get a segmentation fault, if I choose 16000 or 48000 everything is fine. Though choosing a value different than 44100 is making my execution time very bad because a lot of resampling happens.

I would appreciate it if anyone could give me a hint on that.

**Comment by thomasfillon** [comment]
Hi !
The function and the extraction plan seems fine to me. I am able to use the `extractFeatures` function without any problem.
What is the sampling frequency of your audio source file ? Could you also please check with other files ?

**Comment by PGryllos** [comment]
Hi and thank you for the response.

Sorry I didn't realize earlier but this was a specific file related error.
Here is the output

process file /home/xxx/Documents/children_playing/36429.wav
initializing Smarc resampler 11024 => 44100
ERROR: multistage filter output 11024.000000 != 44100 ! (there should be an error in multistage definition)
Smarc resampler ok !
ERROR: cannot initialize reader AudioFileReader for file /home/xxx/Documents/children_playing/36429.wav
process file /home/xxx/Documents/children_playing/15356.aif
Warning: AudioFileReader will convert stereo audio file to mono doing mean of channels
done in 0.019308s
process file /home/xxx/Documents/children_playing/196080.wav
Warning: AudioFileReader will convert stereo audio file to mono doing mean of channels
done in 0.002076s
process file /home/xxx/Documents/children_playing/159735.wav
Warning: AudioFileReader will convert stereo audio file to mono doing mean of channels
Segmentation fault (core dumped)

By deleting  /home/xxx/Documents/children_playing/36429.wav I stopped getting segmentation fault errors. I still don't know what is wrong with that file though.

**Comment by thomasfillon** [comment]
OK thank you for the feedback.
I close this issue.
