### ISSUE TITLE
Docs are down

### ISSUE THREAD

**Issue by hughrawlinson** [Yaafe/Yaafe#17]
The docs, hosted on Sourceforge, are inaccessible because Sourceforge is experiencing infrastructure issues. Given that developers seem to be moving away from Sourceforge generally, would it perhaps be worth moving (or hosting a redundant copy of the docs) on GitHub pages?

**Comment by thomasfillon** [comment]
Hi Hugh !

You fill that issue a long time ago ... sorry to answer it so late ...
The doc seems to be back on Sourceforge, see http://yaafe.sourceforge.net/ and in the meantime I put them on Github pages also : http://yaafe.github.io/Yaafe/

But both are far from being up-to-date ...

I will try to fix this for the 0.70 version that's going to be release soon.

**Comment by hughrawlinson** [comment]
Seeing as the docs are available now, I'll close this ticket and you can open another one for them being out of date. Reopen this ticket if you disagree! 😄
