### ISSUE TITLE
Cmake Issue

### ISSUE THREAD

**Issue by relliottsmith** [Yaafe/Yaafe#18]
Hey-
I am getting this error when I try to ccmake yaafe. Any help?

    CMake Error at src_cpp/yaafe-core/CMakeLists.txt:24 (add_library):
      Cannot find source file:   /Users/rees/Yaafe/externals/fmemopen/fmemopen.c
     Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
      .hxx .in .txx

    CMake Error: CMake can not determine linker language for target: yaafe-core
    CMake Error in src_cpp/yaafe-core/CMakeLists.txt:
      Exporting the target "yaafe-core" is not allowed since its linker language
      cannot be determined

**Comment by ryan-williams** [comment]
seeing the same thing

**Comment by ryan-williams** [comment]
I was able to work around it on OSX by symlinking `fmemopen.{h,c}` [here](https://github.com/NimbusKit/memorymapping/tree/master/src) into `Yaafe/externals/fmemopen/`

**Comment by mckelvin** [comment]
As indicated in [README](https://github.com/Yaafe/Yaafe/blob/master/README.rst#install), please run

```
git submodule init
git submodule update
```

first, these command wills pull fmemopen from remote repo.

**Comment by thomasfillon** [comment]
I close this because it seems that @mckelvin give the proper solution (thank you !).
Don't hesitate to reopen it if you still have the problem.
