### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by AbdealiJK** [Yaafe/Yaafe#19]
Does yaafe work with python3 ?
If not, could it be added ?
If it does, then we should add tests in https://travis-ci.org/Yaafe/Yaafe for py3

**Comment by hbredin** [comment]
Is this live yet? I'd love to be able to use Yaafe in Python 3...

**Comment by hbredin** [comment]
I've noticed that Yaafe now has a `conda` channel.
Would love to use Yaafe in conda with Python 3.
Yaafe is the last library that's blocking me from switching entirely to Python 3.
How can I help, @thomasfillon ?

**Comment by thomasfillon** [comment]
Salut Hervé ! 

Yes it would be great indeed to have Python3 compatibility in Yaafe.

@AbdealiJK it seems that you have done some work to achieve Python3 compatibility. Is it working ? 
If so could you please pull and merge against the Dev branch (https://github.com/Yaafe/Yaafe/tree/dev) and submit a pull request ?

**Comment by thomasfillon** [comment]
Salut Hervé !

Sorry for not being active on this. Could you please help on reviewing #21 ?

**Comment by hbredin** [comment]
I'll try to test this in the coming weeks.

Can you let me know how yaafe's conda packages are built? 
I can't seem to find anything related to conda in the repository.

**Comment by thomasfillon** [comment]
Hi Hervé,

Conda build was done in the dev branch but I've just merge the master and the dev branches.
So now, you could have a look to the conda-recipe directory

**Comment by louisabraham** [comment]
Hi, I'm interested too ! How can I help ?
