### ISSUE TITLE
Licence of the Yaafe Extension 

### ISSUE THREAD

**Issue by louisabraham** [Yaafe/Yaafe#24]
Hello, on the website of the [TP Yaafe Extension](http://perso.telecom-paristech.fr/~essid/tp-yaafe-extension/index.html), it is written that 

> TPYaafeExtension is provided in binary form only and may be used freely for non-commercial purposes only

However, it appears it became open-source (https://sourceforge.net/p/yaafe/mailman/message/33078207/), and it has been merged to the github repository that is under the GNU Lesser General Public License. What is the licence of the TP Yaafe Extension ?

**Comment by thomasfillon** [comment]
Hello,

Yes the TP Yaafe Extension became open-source and has been released under the GNU Lesser General Public License. In fact it has been merged into Yaafe and the  website of the [TP Yaafe Extension](http://perso.telecom-paristech.fr/%7Eessid/tp-yaafe-extension/index.html) is outdated. 
I will asked them to reflect the changes. 
Thank you very much for raising this question.

**Comment by louisabraham** [comment]
Thank you! It's really nice, because it is a very useful project!
Maybe you should add the feature list of the extension to the main site of Yaafe (I found the extension website before because I was looking for a CQT implementation).

**Comment by thomasfillon** [comment]
Thank you !
You're right about the need to update the documentation. 
I add an issue on that point: #25
