### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by thomasfillon** [Yaafe/Yaafe#25]
The documentation should be update to reflect the merge of the former [TP Yaafe Extension](http://perso.telecom-paristech.fr/%7Eessid/tp-yaafe-extension/index.html). 
The TP Yaafe extension features (including CQT and Chroma) should be added to the list of [yaafe core feauture](http://yaafe.github.io/Yaafe/features.html#)

**Comment by louisabraham** [comment]
Be careful, there may be an issue with some functions like CQT2 that are listed on the former extension website and not present in the source code (I only saw one CQT function)

**Comment by thomasfillon** [comment]
It should be fine. The CQT2 code is here : https://github.com/Yaafe/Yaafe/blob/master/src_python/yaafelib/yaafe_extensions/yaafefeatures.py#L982

**Comment by louisabraham** [comment]
I think one should just rebuild the documentation and commit to the gh-pages branch, am I right ?
The generate_features_parameters function of https://github.com/Yaafe/Yaafe/blob/master/src_python/yaafelib/features_doc.py doesn't make any difference between the extension features and the others.

**Comment by louisabraham** [comment]
I don't know why the merge did not close automatically this issue, but it should be closed, no ?

**Comment by thomasfillon** [comment]
yes I close it.
Thank you again !

**Comment by louisabraham** [comment]
I'm sorry, I did it wrong.
There are a lot of error messages like http://yaafe.github.io/Yaafe/features.html#autocorrelation
This is caused by my TeX installation…
