### ISSUE TITLE
Build error with HDF5

### ISSUE THREAD

**Issue by louisabraham** [Yaafe/Yaafe#27]
Hi,

I'm trying to compile with macOS Sierra.
With the option WITH_HDF5=ON, I get the following error :
```
/Users/louisabraham/Downloads/yaafe-v0.65/src_cpp/yaafe-python/yaafecoreH5.cpp:69:56: error: 'H5P_DEFAULT' was not declared in this scope
     hid_t h5file = H5Fopen(h5filename, H5F_ACC_RDONLY, H5P_DEFAULT);
```
I used the command :
```cmake -DWITH_FFTW3=ON -DWITH_HDF5=ON -DWITH_LAPACK=ON -DWITH_MPG123=ON configure ..```
And it found HDF5.
```-- Found HDF5: /opt/local/lib/libhdf5.dylib```

When I try without HDF5 (```cmake -DWITH_FFTW3=ON -DWITH_HDF5=OFF -DWITH_LAPACK=ON -DWITH_MPG123=ON configure ..```), it works fine !

**Comment by thomasfillon** [comment]
Hi,

This issue seems to be the same than #8 and it has been fixed by aca46783cc460 . 
What version of Yaafe are you using ?

**Comment by louisabraham** [comment]
I used v0.65 I downloaded from http://yaafe.github.io/Yaafe/.
I will try cloning the github rep.
Indeed, in the yaafecodeH5.cpp file, the include lines are :

```#ifdef WITH_HDF5
#include "H5Fpublic.h"
#include "H5Gpublic.h"
#include "H5Opublic.h"
#include "H5Dpublic.h"
#include "H5PTpublic.h"
#include "H5LTpublic.h"
#include "H5Tpublic.h"
#include "H5Apublic.h"
#endif```

**Comment by thomasfillon** [comment]
OK fine. Yes please try with the sources from the master branch.
I need to update the doc and the sources link at http://yaafe.github.io/Yaafe/ (see #25 )

**Comment by louisabraham** [comment]
I'm not home, will re try this evening.
Yes, or just give the git clone command.

**Comment by louisabraham** [comment]
It works ! Thank you a lot.

**Comment by thomasfillon** [comment]
Ok great !
