### ISSUE TITLE
Sample rate has no default value

### ISSUE THREAD

**Issue by louisabraham** [Yaafe/Yaafe#29]
When I use `yaafe -f "cqt: CQT" KR.mp3` for example, I get the error "ERROR: please specify sample rate !" though the file has a sample rate (I can see it in its metadata), and the help (`yaafe -h`) specifies :
`  -r SAMPLE_RATE, --rate=SAMPLE_RATE
                        working samplerate in Hz. If not set, use input file
                        sample rate.`

If I add the parameter `yaafe -r 44100 -f "cqt: CQT" KR.mp3`, it just works fine.

**Comment by louisabraham** [comment]
The error is just [here](https://github.com/Yaafe/Yaafe/blob/cac287211cdb628877862e7195820babb627bdb4/src_python/yaafelib/yaafe.py#L163)

**Comment by thomasfillon** [comment]
Well: _It’s not a bug, it’s a feature !_ ;-) 

The specification of the sample rate is a requirement of the `yaafe.py` command line.

Let's suppose that you are extracting some audio features for several audio files (which you can do in the same command line see Yaafe manual [here](http://yaafe.github.io/Yaafe/manual/quickstart.html#extract-over-several-audio-files)).
If the files do not share the same sample rate you would then not be extracting audio features with the same definition.

For example let's consider the default `blocksize` parameters for the MFCC which default value is 1024. It would not correspond to the same window length in seconds if the samplerate is 32000 or 44100 Hz.

By specifying the sample rate in the `yaafe.py` command line:
- you know exactly what you are doing in the time domain (blocksize, stepsize, ...)
- you are sure to process different files with the same feature extraction parameters

Please also note that Yaafe can do the samplerate conversion if needed see Yaafe manual [here](http://yaafe.github.io/Yaafe/manual/quickstart.html#samplerate-conversion).

Is that ok for you ?

**Comment by louisabraham** [comment]
I think there is a contradiction between the documentation and the usage.
I am just a beginner in this field, but I think you almost always use the sample rate of the input file. Why not just read it ?

**Comment by thomasfillon** [comment]
> I think there is a contradiction between the documentation and the usage.

Do you mean that it is not the usage to extract audio features at a sample rate different from the input file ?

One of the main purpose of Yaafe is to extract audio features from several audio files in order to compare those features. If features were extracted with the same parameters but at different sample rate then it would thus mean that they have been extracted with *different* parameters so they can not be compared.

**Comment by louisabraham** [comment]
Ok I understand this is not a bug, but a choice.
We should therefore remove "If not set, use input file sample rate." from the documentation.

**Comment by thomasfillon** [comment]
OK thank you very much for fixing the help message. I didn't notice the contradiction in the `yaafe.py` help message.
