### ISSUE TITLE
Matlab can't open dataflow-file

### ISSUE THREAD

**Issue by lockejan** [Yaafe/Yaafe#36]
Hi there, 

first of all thanks for that powerful toolbox. It's a great tool.
Unfortunately i can't open the dataflow-file within matlab_r2016b. (I'm under Mac OS 10.12.3)
I tried it with the example in the manual and with a textfile-based featureplan as well:
![screenshot 2017-01-31 17 02 09](https://cloud.githubusercontent.com/assets/25434434/22472840/15c0d836-e7d7-11e6-9fcb-390421a899e8.png)

Then i called yaafe in matlab, but as soon as i want to load the flow-file it is giving me an error
```
yaafe.load('yaflow')
cannot open file yaflow
Error while loading flow from file yaflow
ans =

  logical

   0
```
Outside of matlab yaafe is working properly.
Any suggestions?
Thanks in advance

**Comment by thomasfillon** [comment]
Hi,

I'm sorry but I switch to Python for some years now and I don't have any access to Matlab.

Are you sure you are in the proper directory for loading the `yaflow` file from within matlab ? 
Can the yaflow file be read from matlab with regular matlab files I/O functions ?
