### ISSUE TITLE
conda-forge packages

### ISSUE THREAD

**Issue by hbredin** [Yaafe/Yaafe#44]
This issue is meant to keep track of my work on conda-forge packages.

- [x] mpg123
   * Code: https://github.com/hbredin/staged-recipes/tree/master
   * Pull request: https://github.com/conda-forge/staged-recipes/pull/2685
- [x] libsndfile: 
  * Code: https://github.com/hbredin/staged-recipes/tree/feature/libsndfile
  * Pull request: https://github.com/conda-forge/staged-recipes/pull/2689
- [x] argtable2
  * Code: https://github.com/hbredin/staged-recipes/tree/feature/argtable2
  * Pull request: https://github.com/conda-forge/staged-recipes/pull/2688
- [x] yaafe
  * Code: https://github.com/hbredin/staged-recipes/tree/feature/yaafe
  * Pull request: https://github.com/conda-forge/staged-recipes/pull/2709
  * ~~For now, it is based on my own fork of Yaafe (https://github.com/hbredin/staged-recipes/blob/feature/yaafe/recipes/yaafe/meta.yaml#L15).~~
  * ~~A new release of Yaafe with Py3 support and that fixes #41 is still missing.~~
- [ ] Windows support
  * For now, all these packages are Linux and macOS only.

**Comment by hbredin** [comment]
All three `mpg123`, `libsndfile` and `argtable2` recipes passed the continuous integration tests on `conda-forge`. Now waiting for `conda-forge` administrators to merge them...

I cannot make a `conda-forge` pull request for `Yaafe` before:
  - [ ] [`mpg123`](https://github.com/conda-forge/staged-recipes/pull/2685) is merged
  - [ ] [`libsndfile`](https://github.com/conda-forge/staged-recipes/pull/2689) is merged
  - [ ] [`argtable2`](https://github.com/conda-forge/staged-recipes/pull/2688) is merged
  - [ ] a proper Yaafe release with Python 3 support is available on Github
@thomasfillon, `conda-forge` expects `MAJOR.MINOR.PATCH` semantic versioning and does not like hyphens (like in `0.70-rc1`) in version numbers.

**Comment by thomasfillon** [comment]
I've just release 0.70 !

**Comment by hbredin** [comment]
Great. Thanks. Still waiting for other 3 recipes to be merged before sending a pull request to `conda-forge` for Yaafe.

Recipe is here, ready to be `pull request`ed: 
https://github.com/hbredin/staged-recipes/tree/feature/yaafe/recipes/yaafe

**Comment by hbredin** [comment]
All three dependencies now have a conda-forge package. 
Waiting for Yaafe's to build... Getting closer!!!

**Comment by thomasfillon** [comment]
Great ! Merci Hervé !

[Here](https://github.com/conda-forge/staged-recipes/pull/2709) il the link to the corresponding pull request.

**Comment by thomasfillon** [comment]
Great ! [Yaafe is now available on the conda-forge channel](https://anaconda.org/conda-forge/yaafe) .

The only thing that is missing is the windows support.

**Comment by thomasfillon** [comment]
I close this issue. Merci beaucoup @hbredin !

Yaafe can be installed on windows as indicated in the README and thanks to glorious contributors.
To anyone: Feel free to reopen the issue if you think windows installation through Conda is necessary.

**Comment by hbredin** [comment]
@thomasfillon I suggest you add yourself as maintainer of all packages (including mpg123 and argtable2). Remember to increase the build number ;-)

**Comment by thomasfillon** [comment]
ok done !
