### ISSUE TITLE
Possible issue

### ISSUE THREAD

**Issue by louisabraham** [Yaafe/Yaafe#45]
I find this line very disturbing…

    minFreq = decimal.Decimal(params['CQTMinFreq']) * (2 ** (nboct - 1))

from https://github.com/Yaafe/Yaafe/blob/master/src_python/yaafelib/yaafe_extensions/yaafefeatures.py#L929

**Comment by louisabraham** [comment]
Forget it… I did not read the code in depth!
Sorry for the disruption.

**Comment by thomasfillon** [comment]
No problem ! ;-)
