### ISSUE TITLE
os x install using hp5

### ISSUE THREAD

**Issue by davegreenwood** [Yaafe/Yaafe#8]
Hi, if I configure an install `WITH_HDF5` I get the following error (and 4 more similar) with make:

    /yaafe/src_cpp/yaafe-python/yaafecoreH5.cpp:69:56: error: use of undeclared identifier  'H5P_DEFAULT'
    hid_t h5file = H5Fopen(h5filename, H5F_ACC_RDONLY, H5P_DEFAULT);

`H5P_DEFAULT` is defined in "H5Ppublic.h" 
so, by including this file in "yaafe-python/yaafecoreH5.cpp" :

    #ifdef WITH_HDF5
    #include "H5Fpublic.h"
    #include "H5Gpublic.h"
    #include "H5Opublic.h"
    #include "H5Dpublic.h"
    #include "H5Ppublic.h"
    #include "H5PTpublic.h"
    #include "H5LTpublic.h"
    #include "H5Tpublic.h"
    #include "H5Apublic.h"
    #endif

the problem goes away. The question is, is this the proper solution?
many thanks 
Dave Greenwood

**Comment by Crococode** [comment]
How did you configure your setup? Did you set the include path for the HDF5 headers? HDF5_INCLUDE_DIR in CMake.

**Comment by neobonzi** [comment]
I'm having this same issue even after including hdf5_include_dir as /usr/local/include

**Comment by thomasfillon** [comment]
@davegreenwood : it seems a good solution to me.  @Crococode do you agree ?

I had the same issue for installing under Debian Jessie (in Docker) and fix it with the very same solution in aca46783cc460ef119 . 
It seems that the problem appears only with HDF5 library >1.8.14 .

Can we close this issue ?

**Comment by thomasfillon** [comment]
closed by  aca4678
